# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dockform < Formula
  desc "Manage Docker Compose projects declaratively"
  homepage "https://dockform.io"
  version "0.2.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/gcstr/dockform/releases/download/v0.2.2/dockform_v0.2.2_darwin_amd64.tar.gz"
      sha256 "5a93554bfbf3938a82ca186b4419443463384e971baaee3d7759a960ea0c8fb9"

      def install
        bin.install "dockform"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/gcstr/dockform/releases/download/v0.2.2/dockform_v0.2.2_darwin_arm64.tar.gz"
      sha256 "9d1273dbdc1cbc8e7d91a2be3682bec94a7d4900562b2a6f648816c1e64cd7e2"

      def install
        bin.install "dockform"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/gcstr/dockform/releases/download/v0.2.2/dockform_v0.2.2_linux_amd64.tar.gz"
      sha256 "484f2b14309225359a1390dbde0ba18c5e829173b0de333f13ade9d7a7c3ce1d"
      def install
        bin.install "dockform"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/gcstr/dockform/releases/download/v0.2.2/dockform_v0.2.2_linux_arm64.tar.gz"
      sha256 "1133eb0b8013439c962e43d7d0c46b43c725cd8beb35997d0d1aee9184187c3e"
      def install
        bin.install "dockform"
      end
    end
  end

  test do
    system "#{bin}/dockform --version"
  end
end
