# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dockform < Formula
  desc "Manage Docker Compose projects declaratively"
  homepage "https://dockform.io"
  version "0.2.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/gcstr/dockform/releases/download/v0.2.1/dockform_v0.2.1_darwin_amd64.tar.gz"
      sha256 "229f0f30828b5edb02002a223bb8cf9cb22d7e748730242a5d0990b218ec4126"

      def install
        bin.install "dockform"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/gcstr/dockform/releases/download/v0.2.1/dockform_v0.2.1_darwin_arm64.tar.gz"
      sha256 "763a562603b2cd1f7cefb03ad5630b489dce1c071c813bbe9ed86e7832490600"

      def install
        bin.install "dockform"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/gcstr/dockform/releases/download/v0.2.1/dockform_v0.2.1_linux_amd64.tar.gz"
      sha256 "fb406d769b28986a4b9ec8e4f2416d110c77dc48817e876a2825f73934348964"
      def install
        bin.install "dockform"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/gcstr/dockform/releases/download/v0.2.1/dockform_v0.2.1_linux_arm64.tar.gz"
      sha256 "bd94a88d09a5a4987ebfa65fd82261a3baaa8c0ea25334d7a9c68fc6ec7cdf33"
      def install
        bin.install "dockform"
      end
    end
  end

  test do
    system "#{bin}/dockform --version"
  end
end
