# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dockform < Formula
  desc "Manage Docker Compose projects declaratively"
  homepage "https://dockform.io"
  version "0.9.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/gcstr/dockform/releases/download/v0.9.0/dockform_v0.9.0_darwin_amd64.tar.gz"
      sha256 "354308ca986cca182f2450fc0186f493bb53c8fe0320cd0a45fa4ec9d890ffcb"

      define_method(:install) do
        bin.install "dockform"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/gcstr/dockform/releases/download/v0.9.0/dockform_v0.9.0_darwin_arm64.tar.gz"
      sha256 "a91d618d36ce427c54d206b71a1b982d5c991f5d7072f6b2b97d1a075e261bbb"

      define_method(:install) do
        bin.install "dockform"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/gcstr/dockform/releases/download/v0.9.0/dockform_v0.9.0_linux_amd64.tar.gz"
      sha256 "190ce74565485ebfc4ac3aaac1db4e119892bcb91033001eda752733db596d2c"
      define_method(:install) do
        bin.install "dockform"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/gcstr/dockform/releases/download/v0.9.0/dockform_v0.9.0_linux_arm64.tar.gz"
      sha256 "c5d39738a3909c597f3668b54c645e7a047a95d24185416be8ad7dcaeb3f0301"
      define_method(:install) do
        bin.install "dockform"
      end
    end
  end

  test do
    system "#{bin}/dockform --version"
  end
end
