# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dockform < Formula
  desc "Manage Docker Compose projects declaratively"
  homepage "https://dockform.io"
  version "0.6.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/gcstr/dockform/releases/download/v0.6.0/dockform_v0.6.0_darwin_amd64.tar.gz"
      sha256 "b0c0dfb9c743bd2dd0f80e6ee0fc193d4feb17f22dd63a95fee3162499064f96"

      def install
        bin.install "dockform"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/gcstr/dockform/releases/download/v0.6.0/dockform_v0.6.0_darwin_arm64.tar.gz"
      sha256 "2e9abd2a510e46fe665f51edecb5c2329d6c75af9910282d03a412c29b8d19c4"

      def install
        bin.install "dockform"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/gcstr/dockform/releases/download/v0.6.0/dockform_v0.6.0_linux_amd64.tar.gz"
      sha256 "aab284bacb73deaa4c2798cb4bb7ebd7d9b430f33141698e4341b905832425d6"
      def install
        bin.install "dockform"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/gcstr/dockform/releases/download/v0.6.0/dockform_v0.6.0_linux_arm64.tar.gz"
      sha256 "e26a28abe9c4b338afe7b6762e89d75a87979dd763f86c20d0dac0289f69c300"
      def install
        bin.install "dockform"
      end
    end
  end

  test do
    system "#{bin}/dockform --version"
  end
end
